project:
  type: website
  output-dir: docs

website:
  title: "Husni Website"
  favicon: favicon.png
  navbar:
    logo: images/sit_logo_mark.png
    left:
      - href: index.qmd
        text: Home
      - href: Project.qmd
        text: Project
      - href: data-visualization.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: Reflections

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



